name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    #- uses: actions-rust-lang/setup-rust-toolchain@v1
    #  with:
    #    toolchain: 1.79.0
    - name: Setup rust version
      run: rustup default 1.79.0
    - name: Build lcli for x86_64-unknown-linux-gnu
      run:  |
        cargo install cross@0.1.15
        git clone --single-branch --depth=1 -b v5.1.3 https://github.com/sigp/lighthouse
        cd lighthouse
        cross build --bin lcli --target x86_64-unknown-linux-gnu --features "portable,spec-minimal" --profile "maxperf" --locked
        find . -type f -name lcli 2>/dev/null
    # Create release
    - name: Generate release tag
      id: tag
      run: |
        sudo timedatectl set-timezone Asia/Ho_Chi_Minh
        sudo date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"
        echo "release_tag=ActionBuild_${{ matrix.arch }}_$(date +"%Y.%m.%d_%H-%M-%S")" >> $GITHUB_OUTPUT
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
          ./lighthouse/target/x86_64-unknown-linux-gnu/maxperf/lcli
    # Done release

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
